import type { Metadata } from 'next'
import './globals.css'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/authOptions'
import SessionProvider from '@/components/providers/SessionProvider'
import ReactQueryClientProvider from '@/components/providers/ReactQueryClientProvider'
import AuthProvider from '@/components/providers/AuthProvider'

export const metadata: Metadata = {
  title: 'Arundaya',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="font-playfair bg-primary-dark text-white">
        <main className="bg-primary-dark">
          <ReactQueryClientProvider>
            <SessionProvider session={session}>
              <AuthProvider>
                <section className="container min-h-screen relative">{children}</section>
              </AuthProvider>
            </SessionProvider>
          </ReactQueryClientProvider>
        </main>
      </body>
    </html>
  )
}
